# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from conduit._generated import api_pb2 as conduit_dot___generated_dot_api__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in conduit/_generated/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConduitApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTransfer = channel.unary_unary(
                '/conduitapi.ConduitApi/StartTransfer',
                request_serializer=conduit_dot___generated_dot_api__pb2.TransferRequest.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.TransferDetails.FromString,
                _registered_method=True)
        self.StopTransfer = channel.unary_unary(
                '/conduitapi.ConduitApi/StopTransfer',
                request_serializer=conduit_dot___generated_dot_api__pb2.TransferIds.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.MultiTransferDetails.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/conduitapi.ConduitApi/Query',
                request_serializer=conduit_dot___generated_dot_api__pb2.QueryOptions.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.MultiTransferDetails.FromString,
                _registered_method=True)
        self.WatchStatus = channel.unary_stream(
                '/conduitapi.ConduitApi/WatchStatus',
                request_serializer=conduit_dot___generated_dot_api__pb2.TransferIds.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.MultiTransferDetails.FromString,
                _registered_method=True)
        self.GetCert = channel.unary_unary(
                '/conduitapi.ConduitApi/GetCert',
                request_serializer=conduit_dot___generated_dot_api__pb2.CertRequest.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.CertResponse.FromString,
                _registered_method=True)
        self.Version = channel.unary_unary(
                '/conduitapi.ConduitApi/Version',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.VersionInfo.FromString,
                _registered_method=True)
        self.PauseTransfer = channel.unary_unary(
                '/conduitapi.ConduitApi/PauseTransfer',
                request_serializer=conduit_dot___generated_dot_api__pb2.PauseRequest.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.TransferDetails.FromString,
                _registered_method=True)
        self.ValidateTransfer = channel.unary_unary(
                '/conduitapi.ConduitApi/ValidateTransfer',
                request_serializer=conduit_dot___generated_dot_api__pb2.TransferRequest.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.TransferDetails.FromString,
                _registered_method=True)
        self.ServerControl = channel.unary_unary(
                '/conduitapi.ConduitApi/ServerControl',
                request_serializer=conduit_dot___generated_dot_api__pb2.ServerControlRequest.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.ServerControlResponse.FromString,
                _registered_method=True)
        self.SchedulerInfo = channel.unary_unary(
                '/conduitapi.ConduitApi/SchedulerInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.SchedulerInfoResponse.FromString,
                _registered_method=True)
        self.ErrantPaths = channel.unary_unary(
                '/conduitapi.ConduitApi/ErrantPaths',
                request_serializer=conduit_dot___generated_dot_api__pb2.ErrantPathsRequest.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.ErrantPathsResponse.FromString,
                _registered_method=True)
        self.PurgeErrantPath = channel.unary_unary(
                '/conduitapi.ConduitApi/PurgeErrantPath',
                request_serializer=conduit_dot___generated_dot_api__pb2.PurgeErrantPathRequest.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.ErrantPathsResponse.FromString,
                _registered_method=True)


class ConduitApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTransfer(self, request, context):
        """StartTransfer takes in a TransferRequest object and is returned a TransferDetails object with the transfer id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTransfer(self, request, context):
        """StopTransfer takes in a conduit transfer id and is returned a TransferDetails object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Query takes in a query string. If none is provided, it will return details for all transfers for that user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchStatus(self, request, context):
        """WatchStatus takes in a conduit transfer id. If none is provided, it will return a details stream for all transfers for that user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCert(self, request, context):
        """GetCert will authenticate with kerberos and return an mTLS client cert and private key (bundled in a PEM) for that user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Version(self, request, context):
        """Version returns the version info of the conduit server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseTransfer(self, request, context):
        """PauseTransfer will pause all leases in a transfer at a certain state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateTransfer(self, request, context):
        """ValidateTransfer takes in a TransferRequest object and is returned a TransferDetails object with the transfer id. ValidateTransfer will only run validation and will never actually transfer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerControl(self, request, context):
        """ServerControl will shutdown the transfer workers and watchdogs in the conduit server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SchedulerInfo(self, request, context):
        """SchedulerInfo will return information about the scheduler in conduit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ErrantPaths(self, request, context):
        """ErrantPaths will return a list of paths that need to be manually recovered by the user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeErrantPath(self, request, context):
        """PurgeErrantPath will remove an errant path from conduit etcd instance. Returns the paths that were removed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConduitApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTransfer,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.TransferRequest.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.TransferDetails.SerializeToString,
            ),
            'StopTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTransfer,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.TransferIds.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.MultiTransferDetails.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.QueryOptions.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.MultiTransferDetails.SerializeToString,
            ),
            'WatchStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchStatus,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.TransferIds.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.MultiTransferDetails.SerializeToString,
            ),
            'GetCert': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCert,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.CertRequest.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.CertResponse.SerializeToString,
            ),
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.VersionInfo.SerializeToString,
            ),
            'PauseTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseTransfer,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.PauseRequest.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.TransferDetails.SerializeToString,
            ),
            'ValidateTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTransfer,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.TransferRequest.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.TransferDetails.SerializeToString,
            ),
            'ServerControl': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerControl,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.ServerControlRequest.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.ServerControlResponse.SerializeToString,
            ),
            'SchedulerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SchedulerInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.SchedulerInfoResponse.SerializeToString,
            ),
            'ErrantPaths': grpc.unary_unary_rpc_method_handler(
                    servicer.ErrantPaths,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.ErrantPathsRequest.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.ErrantPathsResponse.SerializeToString,
            ),
            'PurgeErrantPath': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeErrantPath,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.PurgeErrantPathRequest.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.ErrantPathsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conduitapi.ConduitApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conduitapi.ConduitApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConduitApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/StartTransfer',
            conduit_dot___generated_dot_api__pb2.TransferRequest.SerializeToString,
            conduit_dot___generated_dot_api__pb2.TransferDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/StopTransfer',
            conduit_dot___generated_dot_api__pb2.TransferIds.SerializeToString,
            conduit_dot___generated_dot_api__pb2.MultiTransferDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/Query',
            conduit_dot___generated_dot_api__pb2.QueryOptions.SerializeToString,
            conduit_dot___generated_dot_api__pb2.MultiTransferDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/conduitapi.ConduitApi/WatchStatus',
            conduit_dot___generated_dot_api__pb2.TransferIds.SerializeToString,
            conduit_dot___generated_dot_api__pb2.MultiTransferDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/GetCert',
            conduit_dot___generated_dot_api__pb2.CertRequest.SerializeToString,
            conduit_dot___generated_dot_api__pb2.CertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/Version',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            conduit_dot___generated_dot_api__pb2.VersionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/PauseTransfer',
            conduit_dot___generated_dot_api__pb2.PauseRequest.SerializeToString,
            conduit_dot___generated_dot_api__pb2.TransferDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/ValidateTransfer',
            conduit_dot___generated_dot_api__pb2.TransferRequest.SerializeToString,
            conduit_dot___generated_dot_api__pb2.TransferDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/ServerControl',
            conduit_dot___generated_dot_api__pb2.ServerControlRequest.SerializeToString,
            conduit_dot___generated_dot_api__pb2.ServerControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SchedulerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/SchedulerInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            conduit_dot___generated_dot_api__pb2.SchedulerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ErrantPaths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/ErrantPaths',
            conduit_dot___generated_dot_api__pb2.ErrantPathsRequest.SerializeToString,
            conduit_dot___generated_dot_api__pb2.ErrantPathsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeErrantPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitApi/PurgeErrantPath',
            conduit_dot___generated_dot_api__pb2.PurgeErrantPathRequest.SerializeToString,
            conduit_dot___generated_dot_api__pb2.ErrantPathsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConduitRunnerApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getNodeStatus = channel.unary_unary(
                '/conduitapi.ConduitRunnerApi/getNodeStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.getNodeStatusStream = channel.unary_stream(
                '/conduitapi.ConduitRunnerApi/getNodeStatusStream',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.submitFTAJob = channel.unary_unary(
                '/conduitapi.ConduitRunnerApi/submitFTAJob',
                request_serializer=conduit_dot___generated_dot_api__pb2.JobRequest.SerializeToString,
                response_deserializer=conduit_dot___generated_dot_api__pb2.NodeStatus.FromString,
                _registered_method=True)


class ConduitRunnerApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getNodeStatusStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submitFTAJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConduitRunnerApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getNodeStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.NodeStatus.SerializeToString,
            ),
            'getNodeStatusStream': grpc.unary_stream_rpc_method_handler(
                    servicer.getNodeStatusStream,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.NodeStatus.SerializeToString,
            ),
            'submitFTAJob': grpc.unary_unary_rpc_method_handler(
                    servicer.submitFTAJob,
                    request_deserializer=conduit_dot___generated_dot_api__pb2.JobRequest.FromString,
                    response_serializer=conduit_dot___generated_dot_api__pb2.NodeStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conduitapi.ConduitRunnerApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conduitapi.ConduitRunnerApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConduitRunnerApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitRunnerApi/getNodeStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            conduit_dot___generated_dot_api__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getNodeStatusStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/conduitapi.ConduitRunnerApi/getNodeStatusStream',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            conduit_dot___generated_dot_api__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submitFTAJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conduitapi.ConduitRunnerApi/submitFTAJob',
            conduit_dot___generated_dot_api__pb2.JobRequest.SerializeToString,
            conduit_dot___generated_dot_api__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
